### ISSUE TITLE
Why the OrigSubsampler has a depthwise+pointwise conv layer after AveragePool?

### ISSUE THREAD

**Issue by Nutingnon** [maorshutman/lenet5-pytorch#1]
Why the OrigSubsampler has a depthwise+pointwise conv layer after AveragePool?

class OrigSubSampler(nn.Module):
    def __init__(self, in_channels=None):
        super(OrigSubSampler, self).__init__()
        self.in_ch = in_channels

        # The number of parameters is 2 * in_channels
        self.s4_1 = nn.AvgPool2d(2, 2)
        self.s4_2 = nn.Conv2d(self.in_ch, self.in_ch, 1, groups=self.in_ch, bias=True)

    def forward(self, x):
        x = self.s4_1(x)
        x = self.s4_2(x) # I don't understand here, is this pointed out in paper?
        return x

**Comment by maorshutman** [comment]
The description of S2 (which is the same as S4) in the paper: "The four inputs to a unit in S2 are added, then multiplied by a trainable coefficient, and added to a trainable bias." 

To get an equivalent calculation with the existing layers, I first average the 2x2 patches (notice that nn.AvgPool2d is depthwise). Then, in order to multiply by a trainable coefficient I used 1x1 depthwise conv which multiplies each channel by a different coefficient. Notice that the number of parameters is just 2 x (number of channels) since the 1x1 conv also has a separate bias for each channel.

**Comment by Nutingnon** [comment]
Understood after your explanation, excellent!! I really learned a lot from your implementation. Thank you very much!
